### ISSUE TITLE
Conda hangs when I try to use environment.yaml

### ISSUE THREAD

**Issue by aseyedia** [Lexogen-Tools/corall_analysis#2]
When I use `./install.sh` or try to create a conda environment using the environment file, conda gets stuck at `Solving Environment` for hours. However, I can just create a conda environment and install the packages manually, though they might not be the same package version. Not sure why this is happening, but just thought I'd let you know.

**Comment by entzian** [comment]
Thanks for this information. Conda is often very slow in solving dependencies. You could use mamba instead of conda for creating environments (https://github.com/mamba-org/mamba or https://anaconda.org/conda-forge/mamba). This is much faster.

**Comment by aseyedia** [comment]
Great! I will try that if the conda environment I made by `conda install`ing each individual package doesn't work. Thank you!
